language: go

branches:
  only:
    - master

go:
  - 1.9

services:
  - docker

sudo: required

env:
  global:
    - REPO: $TRAVIS_REPO_SLUG
    - VERSION: $TRAVIS_TAG

install:
  - docker version
  - go get github.com/golang/lint/golint

script:
  - make validate
  - make test-unit
