logLevel = "debug"
address = ":8080"

[datastore]
    path = "/var/lib/datakube//data/bolt.db"

[storage]
    [storage.file]
        path = "/var/lib/datakube/data/"


[file]
dir = "/var/lib/datakube/"
file = "/var/lib/datakube/targets.toml"