logLevel = "debug"
address = ":8080"

[datastore]
    path = "/var/lib/datahamster/data/bolt.db"

[storage]
    [storage.file]
        path = "/var/lib/datahamster/data/"


[file]
dir = "/var/lib/datahamster/"
file = "/var/lib/datahamster/targets.toml"