[[target]]
    name = "test_target"
    [target.db]
        type = "mysql"
        host = "mariadb"
        name = "test"
        user = "user"
        password = "password"
        port = "3306"
    [target.schedule]
        interval = "every_minute"