logLevel = "debug"
address = ":8080"

[datastore]
    path = "/tmp/datastore"

[storage]
    [storage.file]
        path = "/tmp/filestorage"

[file]
dir = "/Users/manuelzapf/go/src/github.com/SantoDE/datahamster/cmd/server"
file = "/Users/manuelzapf/go/src/github.com/SantoDE/datahamster/cmd/server/targets.toml"