[[target]]
    name = "test_target"
    [target.db]
        type = "mysql"
        host = "localhost"
        name = "test"
        user = "root"
        password = "root"
        port = "3306"
        [target.db.sql]
        tempdir = "/tmp"
    [target.schedule]
        interval = "weekly"
        day = "2"
        at = "03:00"